djangoecommerce/accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register'),
]

djangoecommerce/catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

djangoecommerce/checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(
        r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view,
        name='pagseguro_view'
    ),
    url(
        r'^finalizando/(?P<pk>\d+)/paypal/$', views.paypal_view,
        name='paypal_view'
    ),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(
        r'^notificacoes/pagseguro/$', views.pagseguro_notification,
        name='pagseguro_notification'
    ),
    url(r'^teste/$', views.sells, name='sells'),
    #url(r'^minhas-vendas/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    #url(
    #    r'^notificacoes/pagseguro/$', views.pagseguro_notification,
    #    name='pagseguro_notification'
    #),
]

djangoecommerce/djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url('entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url('sair/', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),
    url(r'^catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^conta/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^compras/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

djangoecommerce/accounts/models.py
# coding=utf-8

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

djangoecommerce/accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']

djangoecommerce/accounts/views.py
# coding=utf-8

from django.shortcuts import render
from django.views.generic import (
    CreateView, TemplateView, UpdateView, FormView
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm

from .models import User
from .forms import UserAdminCreationForm


class IndexView(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/index.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')


class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user


class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)

index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()

djangoecommerce/accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Minha Conta{% endblock %}

{% block container %}
<br>
<br>
<!--<ol class="breadcrumb">
  <li><a href="#">Início</a></li>
  <li class="active">Minha Conta</li>
</ol>-->
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'accounts:index' %}" class="list-group-item active">Minha Conta</a>
          <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
          <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
          <a href="{% url 'checkout:order_list' %}" class="list-group-item">Meus Pedidos</a>
          {% if user.is_staff %}
            <a href="{% url 'checkout:sells' %}" class="list-group-item">Minhas Vendas</a>
          {% endif %}
        </div>
    </div>
    <div class="col-md-8">
        {% block accounts_container %}
            <h2>Bem vindo {{ user }}</h2>
            {% if user.is_superuser %}
                <li><a href="/admin">Página do Administrador</a></li>
            {% endif %}
        {% endblock %}
    </div>
</div>
{% endblock %}

djangoecommerce/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Registro | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Registro</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

djangoecommerce/accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Senha{% endblock %}

{% block accounts_container %}
    <h2>Alterar Senha</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

djangoecommerce/accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}