djangoecommerce/catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

djangoecommerce/checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(
        r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view,
        name='pagseguro_view'
    ),
    url(
        r'^finalizando/(?P<pk>\d+)/paypal/$', views.paypal_view,
        name='paypal_view'
    ),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(
        r'^notificacoes/pagseguro/$', views.pagseguro_notification,
        name='pagseguro_notification'
    ),
    url(r'^teste/$', views.sells, name='sells'),
    #url(r'^minhas-vendas/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    #url(
    #    r'^notificacoes/pagseguro/$', views.pagseguro_notification,
    #    name='pagseguro_notification'
    #),
]

djangoecommerce/djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url('entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url('sair/', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),
    url(r'^catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^conta/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^compras/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

djangoecommerce/checkout/models.py
# coding=utf-8

from pagseguro import PagSeguro

from django.db import models
from django.conf import settings

from catalog.models import Product


class CartItemManager(models.Manager):

    def add_item(self, cart_key, product):
        if self.filter(cart_key=cart_key, product=product).exists():
            created = False
            cart_item = self.get(cart_key=cart_key, product=product)
            cart_item.quantity = cart_item.quantity + 1
            cart_item.save()
        else:
            created = True
            cart_item = CartItem.objects.create(
                cart_key=cart_key, product=product, price=product.price
            )
        return cart_item, created


class CartItem(models.Model):

    cart_key = models.CharField(
        'Chave do Carrinho', max_length=40, db_index=True
    )
    product = models.ForeignKey('catalog.Product', verbose_name='Produto',on_delete='models.CASCADE')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens dos Carrinhos'
        unique_together = (('cart_key', 'product'),)

    def __str__(self):
        return '{} [{}]'.format(self.product, self.quantity)


class OrderManager(models.Manager):

    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order, quantity=cart_item.quantity, product=cart_item.product,
                price=cart_item.price
            )
        return order


class Order(models.Model):

    STATUS_CHOICES = (
        (0, 'Aguardando Pagamento'),
        (1, 'Concluída'),
        (2, 'Cancelada'),
    )

    PAYMENT_OPTION_CHOICES = (
        ('deposit', 'Depósito'),
        ('pagseguro', 'PagSeguro'),
        ('paypal', 'Paypal'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário',on_delete='models.CASCADE')
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=0, blank=True
    )
    payment_option = models.CharField(
        'Opção de Pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20,
        default='deposit'
    )

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return 'Pedido #{}'.format(self.pk)

    def products(self):
        products_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=products_ids)

    def total(self):
        aggregate_queryset = self.items.aggregate(
            total=models.Sum(
                models.F('price') * models.F('quantity'),
                output_field=models.DecimalField()
            )
        )
        return aggregate_queryset['total']

    def pagseguro_update_status(self, status):
        if status == '3':
            self.status = 1
        elif status == '7':
            self.status = 2
        self.save()

    def complete(self):
        self.status = 1
        self.save()

    def pagseguro(self):
        self.payment_option = 'pagseguro'
        self.save()
        pg = PagSeguro(
            email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
            config={'sandbox': settings.PAGSEGURO_SANDBOX}
        )
        pg.sender = {
            'email': self.user.email
        }
        pg.reference_prefix = ''
        pg.shipping = None
        pg.reference = self.pk
        for item in self.items.all():
            pg.items.append(
                {
                    'id': item.product.pk,
                    'description': item.product.name,
                    'quantity': item.quantity,
                    'amount': '%.2f' % item.price
                }
            )
        return pg

    def paypal(self):
        self.payment_option = 'paypal'
        self.save()
        paypal_dict = {
            'upload': '1',
            'business': settings.PAYPAL_EMAIL,
            'invoice': self.pk,
            'cmd': '_cart',
            'currency_code': 'BRL',
            'charset': 'utf-8',
        }
        index = 1
        for item in self.items.all():
            paypal_dict['amount_{}'.format(index)] = '%.2f' % item.price
            paypal_dict['item_name_{}'.format(index)] = item.product.name
            paypal_dict['quantity_{}'.format(index)] = item.quantity
            index = index + 1
        return paypal_dict


class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='items', on_delete='models.CASCADE')
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete='models.CASCADE')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens dos pedidos'

    def __str__(self):
        return '[{}] {}'.format(self.order, self.product)


def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()


models.signals.post_save.connect(
    post_save_cart_item, sender=CartItem, dispatch_uid='post_save_cart_item'
)

djangoecommerce/checkout/views.py
# coding=utf-8

from pagseguro import PagSeguro

from paypal.standard.forms import PayPalPaymentsForm
from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received

from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import (
    RedirectView, TemplateView, ListView, DetailView
)
from django.forms import modelformset_factory
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.conf import settings
from django.http import HttpResponse

from catalog.models import Product

from .models import CartItem, Order


class CreateCartItemView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):

        #quantidade = Product.objects.values_list('quantity', flat=True).get(slug=self.kwargs['slug'])

        #if(quantidade > 0):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        if self.request.session.session_key is None:
            self.request.session.save()
        cart_item, created = CartItem.objects.add_item(
            self.request.session.session_key, product
        )
        if created:
            messages.success(self.request, 'Produto adicionado com sucesso')
            #quantidade -= 1;
            #Product.objects.update(quantity=quantidade)
        else:
            messages.success(self.request, 'Produto atualizado com sucesso')
        return reverse('checkout:cart_item')
        #else:
            #messages.success(self.request, 'Produto indisponível')

class CartItemView(TemplateView):

    template_name = 'checkout/cart.html'

    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(
            CartItem, fields=('quantity',), can_delete=True, extra=0
        )
        session_key = self.request.session.session_key
        if session_key:
            if clear:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key)
                )
            else:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key),
                    data=self.request.POST or None
                )
        else:
            formset = CartItemFormSet(queryset=CartItem.objects.none())
        return formset

    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context

    def post(self, request, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso')
            context['formset'] = self.get_formset(clear=True)
        return self.render_to_response(context)


class CheckoutView(LoginRequiredMixin, TemplateView):

    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_key=session_key).exists():
            cart_items = CartItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(
                user=request.user, cart_items=cart_items
            )
            cart_items.delete()
        else:
            messages.info(request, 'Não há itens no carrinho de compras')
            return redirect('checkout:cart_item')
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response


class OrderListView(LoginRequiredMixin, ListView):

    template_name = 'checkout/order_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('-pk')


class OrderDetailView(LoginRequiredMixin, DetailView):

    template_name = 'checkout/order_detail.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class PagSeguroView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        order_pk = self.kwargs.get('pk')
        order = get_object_or_404(
            Order.objects.filter(user=self.request.user), pk=order_pk
        )
        pg = order.pagseguro()
        pg.redirect_url = self.request.build_absolute_uri(
            reverse('checkout:order_detail', args=[order.pk])
        )
        pg.notification_url = self.request.build_absolute_uri(
            reverse('checkout:pagseguro_notification')
        )
        response = pg.checkout()
        return response.payment_url


class PaypalView(LoginRequiredMixin, TemplateView):

    template_name = 'checkout/paypal.html'

    def get_context_data(self, **kwargs):
        context = super(PaypalView, self).get_context_data(**kwargs)
        order_pk = self.kwargs.get('pk')
        order = get_object_or_404(
            Order.objects.filter(user=self.request.user), pk=order_pk
        )
        paypal_dict = order.paypal()
        paypal_dict['return_url'] = self.request.build_absolute_uri(
            reverse('checkout:order_list')
        )
        paypal_dict['cancel_return'] = self.request.build_absolute_uri(
            reverse('checkout:order_list')
        )
        paypal_dict['notify_url'] = self.request.build_absolute_uri(
            reverse('paypal-ipn')
        )
        context['form'] = PayPalPaymentsForm(initial=paypal_dict)
        return context


@csrf_exempt
def pagseguro_notification(request):
    notification_code = request.POST.get('notificationCode', None)
    if notification_code:
        pg = PagSeguro(
            email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
            config={'sandbox': settings.PAGSEGURO_SANDBOX}
        )
        notification_data = pg.check_notification(notification_code)
        status = notification_data.status
        reference = notification_data.reference
        try:
            order = Order.objects.get(pk=reference)
        except Order.DoesNotExist:
            pass
        else:
            order.pagseguro_update_status(status)
    return HttpResponse('OK')


def paypal_notification(sender, **kwargs):
    ipn_obj = sender
    if ipn_obj.payment_status == ST_PP_COMPLETED and \
        ipn_obj.receiver_email == settings.PAYPAL_EMAIL:
        try:
            order = Order.objects.get(pk=ipn_obj.invoice)
            order.complete()
        except Order.DoesNotExist:
            pass

valid_ipn_received.connect(paypal_notification)


create_cartitem = CreateCartItemView.as_view()
cart_item = CartItemView.as_view()
checkout = CheckoutView.as_view()
order_list = OrderListView.as_view()
order_detail = OrderDetailView.as_view()
pagseguro_view = PagSeguroView.as_view()
paypal_view = PaypalView.as_view()


class SellsView(LoginRequiredMixin, ListView):

    template_name = 'checkout/sells.html'
    paginate_by = 10

    def get_queryset(self):
        return Product.objects.filter(user=self.request.user).order_by('name')


sells = SellsView.as_view()

#produto.values_list('quantity', flat=True).get(pk=1)

djangoecommerce/checkout/templates/checkout/cart.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
Carrinho de Compras
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li class="active">Carrinho de Compras</li>
</ol>
<div class="page-header">
    <h1>Carrinho de Compras</h1>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form class="" action="" method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="table table-bordered">
                <thead>
                    <th>
                        ID
                    </th>
                    <th>
                        Nome
                    </th>
                    <th>
                        Preço
                    </th>
                    <th style="width: 10%;">
                        Quantidade
                    </th>
                    <th>

                    </th>
                </thead>
                <tbody>
                    {% for form in formset %}
                    <tr>
                        <td>
                            {{ form.instance.product.pk }}
                        </td>
                        <td>
                            {{ form.instance.product }}
                        </td>
                        <td>
                            R$ {{ form.instance.price|floatformat:"2" }}
                        </td>
                        <td>
                            {% render_field form.quantity class='form-control' %}
                        </td>
                        <td class="text-center">
                            <button value="on" type="submit" name="{{ form.DELETE.html_name }}" class="btn btn-danger btn-sm">remover</button>
                            {{ form.id }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p class="text-right">
                <a href="{% url 'catalog:product_list' %}" class="pull-left btn btn-default">Continuar Compras</a>
                <button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
                <a href="{% url 'checkout:checkout' %}" class="btn btn-success">Finalizar Compra</a>
            </p>
        </form>
    </div>
</div>
{% endblock %}

djangoecommerce/checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
Finalização da Compra
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
  <li class="active">Finalização da Compra</li>
</ol>
<div class="page-header">
    <h1>Escolha forma de pagamento</h1>
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-2">
        <a href="{% url 'checkout:pagseguro_view' order.pk %}" class="btn btn-success">Pagar com Pagseguro</a>
    </div>
    <div class="col-md-4">
        <a href="{% url 'checkout:paypal_view' order.pk %}" class="btn btn-primary">Pagar com Paypal</a>
    </div>
</div>
{% endblock %}

djangoecommerce/checkout/templates/checkout/order_detail.html
{% extends "accounts/index.html" %}

{% block title %}
Pedido #{{ order.pk }}
{% endblock %}

{% block accounts_container %}
<h2>Pedido #{{ order.pk }}</h2>
<dl class="dl-horizontal">
    <dt>Total R$</dt>
    <dd>{{ object.total|floatformat:"2" }}</dd>
    <dt>Situação</dt>
    <dd>{{ object.get_status_display }}</dd>
    <dt>Data</dt>
    <dd>{{ object.created|date:"d/m/Y H:i" }}</dd>
    <dt>Meio de Pagamento</dt>
    <dd>{{ object.get_payment_option_display }}</dd>
</dl>
<h3>Itens do Pedido</h3>
{% for item in object.items.all %}
    <dl class="dl-horizontal">
        <dt>Produto</dt>
        <dd>{{ item.product }}</dd>
        <dt>Quantidade</dt>
        <dd>{{ item.quantity }}</dd>
        <dt>Preço</dt>
        <dd>R$ {{ item.price|floatformat:"2" }}</dd>
    </dl>
{% endfor %}
{% endblock %}

djangoecommerce/checkout/templates/checkout/order_list.html
{% extends "accounts/index.html" %}

{% load pagination %}

{% block title %}
Meus Pedidos
{% endblock %}

{% block accounts_container %}
<h2>Meus Pedidos</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Produtos
            </th>
            <th>
                Situação
            </th>
            <th>
                Data
            </th>
        </tr>
    </thead>
    <tbody>
        {% for order in object_list %}
        <tr>
            <td>
                <a href="{% url 'checkout:order_detail' order.pk %}">#{{ order.pk }}</a>
            </td>
            <td>
                {% for product in order.products %}
                {{ product.name }}{% if not forloop.last %}<br />{% endif %}
                {% endfor %}
            </td>
            <td>
                {{ order.get_status_display }}
            </td>
            <td>
                {{ order.created|date:"d/m/Y" }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% pagination request paginator page_obj %}
{% endblock %}

djangoecommerce/checkout/templates/checkout/paypal.html
{% extends "base.html" %}

{% block title %}
Pagamento via Paypal
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
  <li class="active">Pagamento via Paypal</li>
</ol>
<div class="page-header">
    <h1>Você está sendo redirecionado para o paypal</h1>
</div>
<div id="paypal" class="row">
    {{ form.render }}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(function(){
        $("#paypal form").submit();
    });
</script>
{% endblock %}

djangoecommerce/checkout/templates/checkout/sells.html
{% extends "accounts/index.html" %}

{% load pagination %}

{% block title %}
Minhas Vendas
{% endblock %}

{% block accounts_container %}
<h2>Minhas Vendas</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th>
                Postado
            </th>
            <th>
                Preço Unid.
            </th>
        </tr>
    </thead>
    <tbody>
        {% for product in object_list %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url}}">{{ product.name }}</a>
            </td>
            <td>
                {{ product.created }}
            </td>
            <td>
                {{ product.price }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% pagination request paginator page_obj %}
{% endblock %}