djangoecommerce/accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register'),
]

djangoecommerce/catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

djangoecommerce/checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(
        r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view,
        name='pagseguro_view'
    ),
    url(
        r'^finalizando/(?P<pk>\d+)/paypal/$', views.paypal_view,
        name='paypal_view'
    ),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(
        r'^notificacoes/pagseguro/$', views.pagseguro_notification,
        name='pagseguro_notification'
    ),
    url(r'^teste/$', views.sells, name='sells'),
    #url(r'^minhas-vendas/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    #url(
    #    r'^notificacoes/pagseguro/$', views.pagseguro_notification,
    #    name='pagseguro_notification'
    #),
]

djangoecommerce/djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url('entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url('sair/', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),
    url(r'^catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^conta/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^compras/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

djangoecommerce/core/models.py
from django.db import models

# Create your models here.

djangoecommerce/core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nE-mail:{1}\n{2}'.format(name, email, message)
        send_mail(
            'Contato do Django E-Commerce', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

djangoecommerce/core/views.py
# coding=utf-8

from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView
from django.contrib.auth import get_user_model

from .forms import ContactForm


User = get_user_model()


class IndexView(TemplateView):

    template_name = 'index.html'


index = IndexView.as_view()


def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contact.html', context)

djangoecommerce/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Silício-Eletrônica{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">Silício-Eletrônica</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
				{% for category in categories %}
				<li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
				{% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
			<form class="navbar-form navbar-left" role="search" action="{% url 'catalog:product_list' %}">
	        <div class="form-group">
	          <input name="q" type="text" class="form-control" placeholder="Pesquisar..." />
	        </div>
			</form>
          <ul class="nav navbar-nav navbar-right">
			<li><a href="{% url 'checkout:cart_item' %}">
				<img src="{% static 'carrinho.png' %}" alt="My">
			</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'accounts:index' %}">Logado como {{ user }}</a></li>
			<li><a href="{% url 'logout' %}">Sair</a></li>
			{% else %}
			<li><a href="{% url 'login' %}">Entrar</a></li>
			<li><a href="{% url 'accounts:register' %}">Registro</a></li>
			{% endif %}
          </ul>
        </div>
      </div>
    </div>
	<br>
	<br>
    <div class="container margin-top">
		{% block messages %}
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }}">
			{{ message }}
		</div>
		{% endfor %}
		{% endblock %}
		{% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="{% url 'index' %}">Início</a></l>
			      <li><a href="{% url 'contact' %}">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

djangoecommerce/core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
    {% endif %}
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

djangoecommerce/core/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="jumbotron page-header">
  <h1>Silício-Eletronica</h1>
  <p>A Silício-Eletrônica é um sistema de e-commerce produzido com foco na venda de produtos eletrônicos, sinta se livre para ver o que temos disponíveis para a compra.</p>
  <!--<p><a class="btn btn-primary">Saiba mais</a></p>-->
</div>
{% endblock %}

djangoecommerce/core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

djangoecommerce/core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
          <ul class="pagination">
              {% for page in paginator.page_range %}
              <li{% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
              {% endfor %}
          </ul>
        </nav>
    </div>
</div>