djangoecommerce/catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

djangoecommerce/checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(
        r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view,
        name='pagseguro_view'
    ),
    url(
        r'^finalizando/(?P<pk>\d+)/paypal/$', views.paypal_view,
        name='paypal_view'
    ),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(
        r'^notificacoes/pagseguro/$', views.pagseguro_notification,
        name='pagseguro_notification'
    ),
    url(r'^teste/$', views.sells, name='sells'),
    #url(r'^minhas-vendas/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    #url(
    #    r'^notificacoes/pagseguro/$', views.pagseguro_notification,
    #    name='pagseguro_notification'
    #),
]

djangoecommerce/djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url('entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url('sair/', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),
    url(r'^catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^conta/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^compras/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

djangoecommerce/catalog/models.py
# coding=utf-8

from django.db import models
from django.urls import reverse
from django.conf import settings


class Category(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})


class Product(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria',on_delete='models.CASCADE')
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário',on_delete='models.CASCADE', default=1)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    image = models.ImageField(
        'Imagem', upload_to='products', blank=True, null=True
    )

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

djangoecommerce/catalog/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic
from watson import search as watson

from .models import Product, Category


class ProductListView(generic.ListView):

    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        queryset = Product.objects.all()
        q = self.request.GET.get('q', '')
        if q:
            queryset = watson.filter(queryset, q)
        return queryset

product_list = ProductListView.as_view()


class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context


category = CategoryListView.as_view()


def product(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product': product
    }
    return render(request, 'catalog/product.html', context)

djangoecommerce/catalog/templates/catalog/_product.html
{% load thumbnail %}
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <a href="{{ product.get_absolute_url }}">
            {% if product.image %}
            <img src="{{ product.image|thumbnail_url:'product_image' }}" alt="" />
            {% else %}
            <img src="http://placehold.it/350x250" alt="" />
            {% endif %}
        </a>
        <div class="caption">
            <h3>{{ product }}</h3>
            {{ product.description|linebreaks }}
            <p><a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a> <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-default" role="button">Adicionar</a></p>
        </div>
    </div>
</div>

djangoecommerce/catalog/templates/catalog/category.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>{{ current_category }}</h1>
</div>
<div class="row">
    {% for product in product_list %}
    {% include "catalog/_product.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}

djangoecommerce/catalog/templates/catalog/product.html
{% extends "base.html" %}

{% block title %}
    {{ product }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{ product }}</h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
          <img src="http://placehold.it/350x250" alt="" />
      </a>
  </div>
  <div class="col-sm-8">
      <p class="text-right">
          <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-success">Adicionar ao Carrinho</a>
      </p>
      {{ product.description|linebreaks }}
  </div>
</div>
{% endblock %}

djangoecommerce/catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for product in products %}
    {% include "catalog/_product.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}